export const planets = {
  Mercury: {
    name: "Mercury",
    description:
      "Dare to taste the chocolate forged in the flames of Mercury? This fiery treat is hotter than the sun!",
    ingredients: [
      "Dark chocolate",
      "Chili",
      "Cinnamon",
      "Fiery orange zest",
      "Volcanic lava extract",
    ],
    nutrition: {
      sugar: "8 g",
      protein: "3 g",
      fat: "9 g",
      carbs: "12 g",
      fiber: "2 g",
      zinc: "0.3 mg",
      iron: "2 mg",
      magnesium: "60 mg",
      vitaminC: "3 mg",
      notable: "Antioxidants, Capsaicin, Orange zest freshness",
    },
    model: "./MercuryModel/Mercury.glb",
    position: [-18, 6, -20],
    color: "#bdbdbd",
    index: 0,
  },
  Venus: {
    name: "Venus",
    description:
      "Venus: Where passion meets chocolate perfection. Get ready to fall in love with every silky bite!",
    ingredients: [
      "Milk chocolate",
      "Velvety caramel center",
      "Rose essence",
      "Crushed hazelnuts",
      "Morning dew drops",
    ],
    nutrition: {
      sugar: "14 g",
      protein: "4 g",
      fat: "11 g",
      carbs: "16 g",
      fiber: "1.5 g",
      zinc: "0.8 mg",
      iron: "1.5 mg",
      vitaminE: "2 mg",
      calcium: "35 mg",
      potassium: "180 mg",
      notable: "Healthy fats, Rose antioxidants, Caramel energy",
    },
    model: "./VenusModel/Venus.glb",
    position: [-22, -5, 22],
    color: "#d4af37",
    index: 1,
  },
  Earth: {
    name: "Earth",
    description:
      "Earth’s chocolate—pure, rich, and real. Are you ready to experience the taste of home like never before?",
    ingredients: [
      "Rich dark chocolate",
      "Roasted almonds",
      "Sea salt",
      "Organic vanilla",
      "Earth’s rich soil essence",
    ],
    nutrition: {
      sugar: "10 g",
      protein: "3 g",
      fat: "8 g",
      carbs: "14 g",
      fiber: "2.5 g",
      zinc: "0.4 mg",
      iron: "2.5 mg",
      magnesium: "55 mg",
      vitaminB6: "0.1 mg",
      potassium: "200 mg",
      notable:
        "Almond omega fats, Sea salt minerals, Vanilla antioxidants",
    },
    model: "./EarthModel/earth.glb",
    position: [18, 10, -20],
    color: "#1f8b4c",
    index: 2,
  },
  Mars: {
    name: "Mars",
    description:
      "Craving adventure? Take a bite of Mars, and let this bold, cosmic chocolate ignite your senses!",
    ingredients: [
      "Milk chocolate",
      "Crunchy hazelnut praline",
      "Espresso",
      "Roasted cocoa nibs",
      "Mars red dust",
    ],
    nutrition: {
      sugar: "12 g",
      protein: "5 g",
      fat: "10 g",
      carbs: "15 g",
      fiber: "2 g",
      zinc: "0.7 mg",
      iron: "2 mg",
      caffeine: "20 mg",
      magnesium: "50 mg",
      vitaminB2: "0.2 mg",
      notable: "Cocoa antioxidants, Energy boost, Hazelnut oils",
    },
    model: "./MarsModel/Mars.glb",
    position: [22, -8, 22],
    color: "#b22222",
    index: 3,
  },
  Jupiter: {
    name: "Jupiter",
    description:
      "Brace yourself for the mighty Jupiter! A colossal chocolate experience that’s as grand as the gas giant itself.",
    ingredients: [
      "Triple-layered chocolate",
      "Caramel",
      "Nougat",
      "Crushed pecans",
      "Jupiter’s storm particles",
    ],
    nutrition: {
      sugar: "16 g",
      protein: "4 g",
      fat: "12 g",
      carbs: "18 g",
      fiber: "2.5 g",
      zinc: "0.6 mg",
      iron: "2 mg",
      magnesium: "40 mg",
      calcium: "45 mg",
      potassium: "210 mg",
      notable: "Pecan fats, Caramel energy, Colossal richness",
    },
    model: "./JupiterModel/Jupiter.glb",
    position: [-18, 4, 35],
    color: "#d2691e",
    index: 4,
  },
  Saturn: {
    name: "Saturn",
    description:
      "Saturn’s rings hold a secret… a galaxy of flavors waiting to be discovered. One bite, and you’ll be orbiting!",
    ingredients: [
      "White chocolate",
      "Dark chocolate swirls",
      "Citrus mousse",
      "Golden sugar crystals",
      "Saturn’s ring dust",
    ],
    nutrition: {
      sugar: "15 g",
      protein: "3 g",
      fat: "11 g",
      carbs: "17 g",
      fiber: "1.8 g",
      zinc: "0.4 mg",
      calcium: "50 mg",
      iron: "1.2 mg",
      vitaminC: "2 mg",
      potassium: "190 mg",
      notable: "Citrusy freshness, Golden sugar, Dual chocolate mix",
    },
    model: "./SaturnModel/Saturn.glb",
    position: [30, 4, 15],
    color: "#f4a460",
    index: 5,
  },
  Uranus: {
    name: "Uranus",
    description:
      "Cold, crisp, and out of this world. Uranus brings an unexpected twist that will leave your taste buds floating!",
    ingredients: [
      "Dark chocolate",
      "Mint",
      "Crispy rice pearls",
      "Mint ganache",
      "Uranus’s icy breeze",
    ],
    nutrition: {
      sugar: "9 g",
      protein: "2.5 g",
      fat: "7 g",
      carbs: "11 g",
      fiber: "2 g",
      zinc: "0.5 mg",
      iron: "1.8 mg",
      magnesium: "45 mg",
      vitaminK: "1 mcg",
      calcium: "25 mg",
      notable: "Mint coolness, Crispy crunch, Light texture",
    },
    model: "./UranusModel/Uranus.glb",
    position: [-28, -5, -20],
    size: 2,
    color: "#afeeee",
    index: 6,
  },
  Neptune: {
    name: "Neptune",
    description:
      "Dive into the depths of Neptune’s ocean with deep, decadent dark chocolate. Can you handle the depth of this delight?",
    ingredients: [
      "Deep dark chocolate",
      "Sea salt",
      "Blueberry",
      "Chocolate drizzle",
      "Neptune’s deep ocean water",
    ],
    nutrition: {
      sugar: "11 g",
      protein: "3 g",
      fat: "9 g",
      carbs: "13 g",
      fiber: "2.2 g",
      zinc: "0.4 mg",
      iron: "2 mg",
      magnesium: "50 mg",
      vitaminA: "30 IU",
      potassium: "175 mg",
      notable:
        "Blueberry antioxidants, Ocean minerals, Deep cocoa taste",
    },
    model: "./NeptuneModel/Neptune.glb",
    position: [16, -8, -26],
    color: "#4169e1",
    index: 7,
  },
  Sun: {
    name: "Sun",
    description:
      "The ultimate luxury reserved only for our VIP customers. Experience the brilliance and warmth of the Sun in every lavish bite!",
    ingredients: [
      "Golden caramel",
      "24-carat gold flakes",
      "Sun-dried vanilla beans",
      "Silky chocolate",
      "Essence of the Sun",
    ],
    nutrition: {
      sugar: "18 g",
      protein: "4 g",
      fat: "13 g",
      carbs: "20 g",
      fiber: "1.5 g",
      zinc: "0.6 mg",
      iron: "2 mg",
      calcium: "40 mg",
      magnesium: "35 mg",
      vitaminD: "trace",
      gold: "trace",
      notable: "Golden caramel, Vanilla aroma, Radiant warmth",
    },
    model: "./SunModel/Sun.glb",
    position: [0, 0, 0],
    color: "#ffdf00",
    index: 8,
  },
};
